Adequate: contain name:false, contain value: true, close to manual: false, close to all user descs: false, mutated: io.bytes.per.checksum, with value: 486528527, message: Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=486528527) must divide block size (=134217728)., status: Fail
Adequate: contain name:false, contain value: true, close to manual: false, close to all user descs: false, mutated: io.bytes.per.checksum, with value: 486528527, message: Task: attempt_1701457076904_0340_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=486528527) must divide block size (=134217728)., status: Fail
Adequate: contain name:false, contain value: true, close to manual: false, close to all user descs: false, mutated: io.bytes.per.checksum, with value: 486528527, message: Diagnostics report from attempt_1701457076904_0340_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=486528527) must divide block size (=134217728)., status: Fail
