name,value,relevant log,explanation
io.bytes.per.checksum,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
ftp.replication,3,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
io.map.index.interval,128,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	io
io.bytes.per.checksum,0,INFO	Diagnostics report from attempt_1701457076904_0039_m_000004_0: [2023-12-02 04:01:54.326]Exception when trying to cleanup container container_1701457076904_0039_01_000008: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701457076904_0039/container_1701457076904_0039_01_000008/container_1701457076904_0039_01_000008.pid (No such file or directory)	,value-hit
dfs.datanode.directoryscan.threads,1,INFO	Diagnostics report from attempt_1701457076904_0039_m_000004_0: [2023-12-02 04:01:54.326]Exception when trying to cleanup container container_1701457076904_0039_01_000008: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701457076904_0039/container_1701457076904_0039_01_000008/container_1701457076904_0039_01_000008.pid (No such file or directory)	,value-hit
ftp.replication,3,INFO	Diagnostics report from attempt_1701457076904_0039_m_000004_0: [2023-12-02 04:01:54.326]Exception when trying to cleanup container container_1701457076904_0039_01_000008: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701457076904_0039/container_1701457076904_0039_01_000008/container_1701457076904_0039_01_000008.pid (No such file or directory)	,value-hit
dfs.namenode.get-blocks.max-qps,20,INFO	Diagnostics report from attempt_1701457076904_0039_m_000004_0: [2023-12-02 04:01:54.326]Exception when trying to cleanup container container_1701457076904_0039_01_000008: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701457076904_0039/container_1701457076904_0039_01_000008/container_1701457076904_0039_01_000008.pid (No such file or directory)	,value-hit
io.map.index.interval,128,INFO	Diagnostics report from attempt_1701457076904_0039_m_000004_0: [2023-12-02 04:01:54.326]Exception when trying to cleanup container container_1701457076904_0039_01_000008: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701457076904_0039/container_1701457076904_0039_01_000008/container_1701457076904_0039_01_000008.pid (No such file or directory)	,property-item-hit	io
io.bytes.per.checksum,0,"ERROR	Task: attempt_1701457076904_0039_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.datanode.directoryscan.threads,1,"ERROR	Task: attempt_1701457076904_0039_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
ftp.replication,3,"ERROR	Task: attempt_1701457076904_0039_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
io.map.index.interval,128,"ERROR	Task: attempt_1701457076904_0039_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	io
io.bytes.per.checksum,0,"INFO	Diagnostics report from attempt_1701457076904_0039_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.datanode.directoryscan.threads,1,"INFO	Diagnostics report from attempt_1701457076904_0039_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
ftp.replication,3,"INFO	Diagnostics report from attempt_1701457076904_0039_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
io.map.index.interval,128,"INFO	Diagnostics report from attempt_1701457076904_0039_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	io
dfs.datanode.directoryscan.threads,1,INFO	1 failures on node ed761ad59d44,value-hit
io.bytes.per.checksum,0,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
io.map.index.interval,128,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,0,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
io.map.index.interval,128,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,0,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.map.index.interval,128,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,0,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
dfs.datanode.directoryscan.threads,1,INFO	Exiting with status 1: java.lang.NullPointerException,value-hit
io.map.index.interval,128,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
