dfs.client.max.block.acquire.failures	3	ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).
		30