Adequate: contain name:false, contain value: true, close to manual: false, close to all user descs: false, mutated: io.bytes.per.checksum, with value: -232574920, message: Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-232574920, effective=null, status: Fail
Adequate: contain name:false, contain value: true, close to manual: false, close to all user descs: false, mutated: io.bytes.per.checksum, with value: -232574920, message: Task: attempt_1701312551309_0542_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-232574920, effective=null, status: Fail
Adequate: contain name:false, contain value: true, close to manual: false, close to all user descs: false, mutated: io.bytes.per.checksum, with value: -232574920, message: Diagnostics report from attempt_1701312551309_0542_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-232574920, effective=null, status: Fail
