name,value,relevant log,explanation
io.bytes.per.checksum,303273923,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1565501989
	",property-item-hit	io
yarn.resourcemanager.nm-container-queuing.max-queue-length,15,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1565501989
	",value-hit
hadoop.fuse.timer.period,5,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1565501989
	",value-hit
yarn.client.max-cached-nodemanagers-proxies,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1565501989
	",value-hit
ha.failover-controller.graceful-fence.rpc-timeout.ms,5000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1565501989
	",property-item-hit	ha
ipc.server.purge.interval,15,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1565501989
	",value-hit
io.bytes.per.checksum,303273923,ERROR	Task: attempt_1701312551309_0543_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1565501989	,property-item-hit	io
yarn.resourcemanager.nm-container-queuing.max-queue-length,15,ERROR	Task: attempt_1701312551309_0543_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1565501989	,value-hit
hadoop.fuse.timer.period,5,ERROR	Task: attempt_1701312551309_0543_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1565501989	,value-hit
yarn.client.max-cached-nodemanagers-proxies,0,ERROR	Task: attempt_1701312551309_0543_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1565501989	,value-hit
yarn.app.mapreduce.client-am.ipc.max-retries,3,ERROR	Task: attempt_1701312551309_0543_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1565501989	,value-hit
ipc.server.purge.interval,15,ERROR	Task: attempt_1701312551309_0543_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1565501989	,value-hit
io.bytes.per.checksum,303273923,INFO	Diagnostics report from attempt_1701312551309_0543_r_000000_0: Error: java.lang.NegativeArraySizeException: -1565501989	,property-item-hit	io
yarn.resourcemanager.nm-container-queuing.max-queue-length,15,INFO	Diagnostics report from attempt_1701312551309_0543_r_000000_0: Error: java.lang.NegativeArraySizeException: -1565501989	,value-hit
hadoop.fuse.timer.period,5,INFO	Diagnostics report from attempt_1701312551309_0543_r_000000_0: Error: java.lang.NegativeArraySizeException: -1565501989	,value-hit
yarn.client.max-cached-nodemanagers-proxies,0,INFO	Diagnostics report from attempt_1701312551309_0543_r_000000_0: Error: java.lang.NegativeArraySizeException: -1565501989	,value-hit
yarn.app.mapreduce.client-am.ipc.max-retries,3,INFO	Diagnostics report from attempt_1701312551309_0543_r_000000_0: Error: java.lang.NegativeArraySizeException: -1565501989	,value-hit
ipc.server.purge.interval,15,INFO	Diagnostics report from attempt_1701312551309_0543_r_000000_0: Error: java.lang.NegativeArraySizeException: -1565501989	,value-hit
hadoop.fuse.timer.period,5,INFO	1 failures on node cf6e5ca2712c,value-hit
io.bytes.per.checksum,303273923,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
ha.failover-controller.graceful-fence.rpc-timeout.ms,5000,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	ha
io.bytes.per.checksum,303273923,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
ha.failover-controller.graceful-fence.rpc-timeout.ms,5000,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	ha
io.bytes.per.checksum,303273923,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,303273923,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
